[project]
name = "soton-hackstart-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "hfoster08" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
soton-hackstart-2026 = "soton_hackstart_2026:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
